### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by vicentyang** [lqs469/jump#1]
打开127.0.0.1:8100 有json返回
npm start 时候报这个错误
(node:53974) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: invalid json response body at http://127.0.0.1:8100/status reason: Unexpected end of JSON input
(node:53974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lqs469** [comment]
@vicentyang 没法准确判断问题, 如果重试后必复现的话, 断开设备重启WDA再重试一下, 注意看WDA的输出是否没有报错, 转发端口是否正常. 另外最好提供一下xcode, ios, node等版本信息.
