### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by tianheng2017** [lqs469/jump#11]
administratordeMacBook-Air:WebDriverAgent administrator$ npm start

> jump@1.0.0 start /Users/administrator/WebDriverAgent
> babel-node index.js

/Users/administrator/WebDriverAgent/index.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at loader (/Users/administrator/WebDriverAgent/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/administrator/WebDriverAgent/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at Object.<anonymous> (/Users/administrator/WebDriverAgent/node_modules/babel-cli/lib/_babel-node.js:154:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2018-01-09T04_29_49_647Z-debug.log
administratordeMacBook-Air:WebDriverAgent administrator$

**Comment by lqs469** [comment]
Update Node.js version to lastest, `npm install`, try again.

**Comment by tianheng2017** [comment]
已降低nodejs版本还是不行！


administratordeMacBook-Air:WebDriverAgent administrator$ npm -v
5.5.1
administratordeMacBook-Air:WebDriverAgent administrator$ node -v
v9.3.0

**Comment by tianheng2017** [comment]
administratordeMacBook-Air:WebDriverAgent administrator$ npm start

> jump@1.0.0 start /Users/administrator/WebDriverAgent
> babel-node index.js

/Users/administrator/WebDriverAgent/index.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at loader (/Users/administrator/WebDriverAgent/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/administrator/WebDriverAgent/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at Object.<anonymous> (/Users/administrator/WebDriverAgent/node_modules/babel-cli/lib/_babel-node.js:154:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2018-01-09T05_29_58_725Z-debug.log
administratordeMacBook-Air:WebDriverAgent administrator$

**Comment by tianheng2017** [comment]
administratordeMacBook-Air:WebDriverAgent administrator$ npm install
npm WARN jump@1.0.0 No repository field

**Comment by lqs469** [comment]
@tianheng2017 你为什么要降低Nodejs版本? 你的安装没有成功, 升级node以及npm的版本.

**Comment by tianheng2017** [comment]
已升级到最新版了，还是不行install不成功，帮我看看，谢谢您了！
administratordeMacBook-Air:WebDriverAgent administrator$ node -v
v9.3.0
administratordeMacBook-Air:WebDriverAgent administrator$ npm -v
5.6.0
administratordeMacBook-Air:WebDriverAgent administrator$ ls
CONTRIBUTING.md			WebDriverAgentRunner
Cartfile			WebDriverAgentTests
Cartfile.resolved		config.js
Carthage			index.html
Configurations			index.js
Inspector			inspec.jpg
LICENSE				jump1.gif
PATENTS				node_modules
PrivateHeaders			npm-debug.log
README.md			package-lock.json
Resources			package.json
Scripts				sharp.js
WebDriverAgent.xcodeproj	yarn.lock
WebDriverAgentLib
administratordeMacBook-Air:WebDriverAgent administrator$ npm install
npm WARN jump@1.0.0 No repository field.

up to date in 4.064s
administratordeMacBook-Air:WebDriverAgent administrator$

**Comment by tianheng2017** [comment]
另外问一下这个源码下载好了是直接放到WebDriverAgent根目录还是inspector目录？

**Comment by tianheng2017** [comment]
我是小白，弄了一上午了，快要崩溃了，升级到最新版的nodejs（v9.3.0）和npm(v5.6.0)还是语法错误

**Comment by tianheng2017** [comment]
我查阅资料，在package.json里面加入了一句："private":true,     npm install没问题了，可是还是有语法错误，提示import那个

**Comment by lqs469** [comment]
@tianheng2017 不用放在任何目录下, 跟WDA分离, 单独安装和启动.

**Comment by tianheng2017** [comment]
原来如此，我分离开了，import错误没有了，现在是新的错误！
administratordeMacBook-Air:jump administrator$ npm i
up to date in 1.941s
administratordeMacBook-Air:jump administrator$ npm start

> jump@1.0.0 start /Users/administrator/Downloads/jump
> babel-node index.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'sharp'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/administrator/Downloads/jump/index.js:5:1)
    at Module._compile (module.js:660:30)
    at loader (/Users/administrator/Downloads/jump/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/administrator/Downloads/jump/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2018-01-09T07_42_18_646Z-debug.log
administratordeMacBook-Air:jump administrator$

**Comment by tianheng2017** [comment]
npm install sharp后不报错了，执行npm start卡住不动了，游戏也不跳


administratordeMacBook-Air:jump administrator$ npm install
up to date in 1.893s
administratordeMacBook-Air:jump administrator$ npm start

> jump@1.0.0 start /Users/administrator/Downloads/jump
> babel-node index.js

**Comment by lqs469** [comment]
@tianheng2017 输出我看一下

**Comment by tianheng2017** [comment]
npm install sharp后不报错了，执行npm start卡住不动了，游戏也不跳


administratordeMacBook-Air:jump administrator$ npm install
up to date in 1.893s
administratordeMacBook-Air:jump administrator$ npm start

> jump@1.0.0 start /Users/administrator/Downloads/jump
> babel-node index.js

**Comment by tianheng2017** [comment]
搞定了，感谢你！要跳了，不过悲剧的是我是iphone 6s plus，似乎第一次就跳到外面去了

**Comment by tianheng2017** [comment]
Frist point 904 826 182 182 190
middle 906
[ center ] 906 987
{ x: 396.66356107660454, y: 1272.0155279503106 } { x: 906, y: 987 }
(509.33643892339546, 285.01552795031057) 
[distance]: 583.6586838109753  [time]:1.7745504824862357
[lastScreen18.png saved]

**Comment by tianheng2017** [comment]
这个不同机型的参数算法是修改index.js吧？

**Comment by lqs469** [comment]
@tianheng2017 修改config文件即可

**Comment by tianheng2017** [comment]
谢谢，请问b和k代表什么，我研究出来了公布机型参数

**Comment by tianheng2017** [comment]
哦  我读了下，虽然没学过python，感觉与距离和时间有关

**Comment by lqs469** [comment]
@tianheng2017 额.. 这是JS...

**Comment by tianheng2017** [comment]
没看懂f和t代表什么

**Comment by lqs469** [comment]
@tianheng2017 f 起跳点, t 目标点

**Comment by tianheng2017** [comment]
懂了，d是距离，代表三角形的玄

**Comment by tianheng2017** [comment]
要怎么算出b和k

**Comment by tianheng2017** [comment]
我用ps把辅助线都画好了

**Comment by tianheng2017** [comment]
我试了下 iphone 6s plus这对参数可以使用const config = {
  b: 55.229,
  k: 302.884
}

**Comment by tianheng2017** [comment]
晚上我优化下 ，看能不能跳到正中间

**Comment by tianheng2017** [comment]
IPHONE 6s plus  比较好的配置：
const config = {
  b: 55.2,
  k: 303
}
我已经跳到137分了  应该没什么问题

**Comment by tianheng2017** [comment]
我始终是蒙的，有没有计算方法怎么取值？
刚刚跳到144掉了
