### ISSUE TITLE
请问下设备参数b k是啥意思？设备分辨率还是？

### ISSUE THREAD

**Issue by Lobster-King** [lqs469/jump#12]
请问下设备参数b k是啥意思？设备分辨率还是？

**Comment by zhangdc** [comment]
const iphone7 = { b: 55.229, k: 188.815, top: 300 }
const iphoneX = { b: 141, k: 308.205, top:600 }
const iphone6 = {}
const iphone6p = {}
const iphoneSE = {}
const iphone8 = {}
const iphone8p = {}

作者能帮忙解释下什么意思吗，b,k,top，可以的话大家不都能立马帮你补上参数了嘛

**Comment by lqs469** [comment]
y = kx^2 + b 
x是时间，y是距离。
top是不同设备顶部留出的距离，从此处开始往下遍历像素点的（目的是避免分数和按钮的干扰）

**Comment by zhangdc** [comment]
@lqs469 我还是没看明白。。。如果说像素的话，iPhone 7和6的像素不是一样的吗？那参数7和6的不就一样了？我用7的参数在6上面会直接跳出屏幕

**Comment by lqs469** [comment]
@zhangdc 看分辨率, 7和6的分辨率不一样(比如X比7大一点点, 但分辨率却是7的接近两倍)

**Comment by zhangdc** [comment]
@lqs469 

设备 | 屏幕尺寸 | 分辨率（pt） | Reader | 分辨率（px） | 渲染后 | PPI
iPhone 6 | 4.7吋 | 375x667 | @2x | 750x1334 |   | 326
iPhone 6s | 4.7吋 | 375x667 | @2x | 750x1334 |   | 326
iPhone 7 | 4.7吋 | 375x667 | @2x | 750x1334 |   | 326

这三个设备的分辨率是一样的吧？

**Comment by lqs469** [comment]
@zhangdc 只能说软件的逻辑分辨率不同吧, 不然没法解释为什么同样机型可以通用, 同样尺寸机型却不能通用. 你可以深究一下这个问题.

**Comment by zhangdc** [comment]
@lqs469 我使用你现有的iPhone X参数，然后用iPhone X真机执行命令，还是会一直蓄力，然后就飞出屏幕了。。。

**Comment by lqs469** [comment]
@zhangdc 这... 我没有遇到过你这个情况...暂时没法给你解决方法...持续关注...
