### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by Cyrix686** [lqs469/jump#2]
截止到npm start命令行之前的步骤都已经完成，可以在8100端口页面看到相关内容，执行npm start命令之后，出错，提示：

$ npm start

> jump@1.0.0 start /Users/alex/Downloads/jump-master
> babel-node index.js

sh: babel-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-01-05T02_35_20_902Z-debug.log

log文件内容如下：

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jump@1.0.0~prestart: jump@1.0.0
6 info lifecycle jump@1.0.0~start: jump@1.0.0
7 verbose lifecycle jump@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle jump@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alex/Downloads/jump-master/node_modules/.bin:/Users/alex/.pyenv/shims:/Users/alex/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/alex/.rvm/bin:/sbin/
9 verbose lifecycle jump@1.0.0~start: CWD: /Users/alex/Downloads/jump-master
10 silly lifecycle jump@1.0.0~start: Args: [ '-c', 'babel-node index.js' ]
11 info lifecycle jump@1.0.0~start: Failed to exec start script
12 verbose stack Error: jump@1.0.0 start: `babel-node index.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid jump@1.0.0
14 verbose cwd /Users/alex/Downloads/jump-master
15 verbose Darwin 17.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v8.9.4
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error jump@1.0.0 start: `babel-node index.js`
23 error spawn ENOENT
24 error Failed at the jump@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by vicentyang** [comment]
@Cyrix686 
sh: babel-node: command not found

没有执行 npm install?

**Comment by heyz-lzj** [comment]
jump-master npm install 
npm WARN jump@1.0.0 No repository field.
➜  jump-master npm start  

> jump@1.0.0 start /Users/heyz3a/Downloads/jump-master
> babel-node index.js

/Users/heyz3a/Downloads/jump-master/index.js:189
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (/Users/heyz3a/Downloads/jump-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/heyz3a/Downloads/jump-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (/Users/heyz3a/Downloads/jump-master/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:570:32)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/heyz3a/.nvm/versions/node/v6.10.0/bin/node" "/Users/heyz3a/.nvm/versions/node/v6.10.0/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script 'babel-node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/heyz3a/Downloads/jump-master/npm-debug.log
➜  jump-master

**Comment by lqs469** [comment]
@Cyrix686 是因为async function不支持, node是从7.6开始支持async的, 升级你的node版本再试试.

**Comment by Cyrix686** [comment]
嗯，确实是少了npm install这个步骤！

**Comment by Cyrix686** [comment]
可以运行了，但是第一跳就跳老远了，然后error了。。。

npm start

> jump@1.0.0 start /Users/alex/Downloads/jump-master
> babel-node index.js

File saved.
178 180 192 220 250
{ x: 396.82553191489365, y: 1266.4925531914894 } { x: 220, y: 250 }
(176.82553191489365, 966.4925531914894) 
[distance]:  982.5350498132822  [time]:3.7710677746883583
2.2616500764838112
File saved.
File saved.
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'i' of undefined
    at /Users/alex/Downloads/jump-master/index.js:148:17
    at /Users/alex/Downloads/jump-master/node_modules/get-pixels/node-pixels.js:22:5
    at exports.PNG.<anonymous> (/Users/alex/Downloads/jump-master/node_modules/pngjs/lib/png.js:74:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at exports.PNG.emit (events.js:211:7)
    at exports.PNG.<anonymous> (/Users/alex/Downloads/jump-master/node_modules/pngjs/lib/png.js:36:10)
    at emitOne (events.js:116:13)
    at module.exports.emit (events.js:211:7)
    at module.exports.ParserAsync._complete (/Users/alex/Downloads/jump-master/node_modules/pngjs/lib/parser-async.js:109:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-01-05T06_37_37_735Z-debug.log

**Comment by lqs469** [comment]
@Cyrix686 你的机型是什么的?

**Comment by Cyrix686** [comment]
8 Plus

**Comment by m00nfly** [comment]
看到作者是在 iphone 7 上测试成功的，是否根机型有关系？
屏幕分辨率尺寸的差异可能会导致算法找不到正确的定位点？我的是 7P 也是出现这个问题！

**Comment by lqs469** [comment]
#5 热烈欢迎提供别的设备参数
