### ISSUE TITLE
关于第一下直接蓄力飞出去的

### ISSUE THREAD

**Issue by Cflelf** [lqs469/jump#6]
该算法会把分数当成第一个方块，因此getT时，纵坐标应该从下面一些开始循环，我改成700后没有问题，但是距离还是有一些奇怪

**Comment by lqs469** [comment]
@Cflelf 为避开顶部分数等一些干扰, 代码从y = 250开始往下找, 这个iPhone7上的一个经验值, 不过在不同分辨率设备上可能不能完全避开, 需要放大这个值

**Comment by Cflelf** [comment]
对的，而且颜色的判断也要改，我觉得可以把背景色先提取，然后找到第一个与背景色差20的，还有目标的中心点不一定是y-50，如果半径太小，会直接掉下去
